name: Codacy Auto-Fix

on: [push, pull_request]

jobs:
  auto_fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install auto-fix tools
        run: pip install black flake8 pylint

      - name: Auto-format code
        run: |
          black .
          flake8 . --max-line-length=100

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-fix: formatted code using Black & Flake8"
