name: Codacy Auto-Fix

on: [push, pull_request]

jobs:
  auto_fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verify repository contents
        run: ls -la

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black flake8 pylint
          pip install pandas numpy scikit-learn tensorflow requests textblob gspread oauth2client yfinance matplotlib seaborn fpdf psutil dotenv gym stable_baselines3 scipy schedule

      - name: Auto-format code with Black
        run: black .

      - name: Lint with Flake8
        run: flake8 . --max-line-length=120 --select=E,F,W || true

      - name: Lint with Pylint
        run: pylint --disable=C,R,W . || true

      - name: Auto-format and commit
        run: |
          black .
          git add .
          git commit -m "Auto-fix: formatted code using Black, Flake8 & Pylint" || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
