name: Codacy Auto-Fix

on: [push, pull_request]

jobs:
  auto_fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Använder din nya token för att få skrivåtkomst

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install auto-fix tools
        run: pip install black flake8 pylint

      - name: Auto-format code
        run: |
          black .
          flake8 . --max-line-length=100 || true

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-fix: formatted code using Black & Flake8"
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Skilleee <Skilleee@users.noreply.github.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Använd token här också för push-rättigheter